### ISSUE TITLE
​

### ISSUE THREAD

**Issue by Neubulae** [hYdos/Blaze4D#7]

**Comment by IMS212** [comment]
High priority, please fix @hYdos

**Comment by Neubulae** [comment]
yes yes this has cause severe impact to my game and Linux install

**Comment by hYdos** [comment]
fixed

**Comment by Neubulae** [comment]
:hmpf: it be no fix I recompiel and mye arch insatall is stil broenkn

**Comment by IMS212** [comment]
this fix doesn't work

**Comment by Fishvap** [comment]
Please fix it hYdos I can't play Minecraft this bug is high priority

**Comment by Sorenon** [comment]
forge?

**Comment by BasiqueEvangelist** [comment]
> forge?

forgor? :skull:

**Comment by Neubulae** [comment]
I'm deeply grieved by the sole existence of this issue as it remained not fixed for months while being locked behind a wannabe authority like Blaze4D organization, #revoltForDemocracy

**Comment by burgerguy** [comment]
> I'm deeply grieved by the sole existence of this issue as it remained not fixed for months while being locked behind a wannabe authority like Blaze4D organization, #revoltForDemocracy

i agree but will do nothing about it

**Comment by ramidzkh** [comment]
fine, everyone will be equal
in having no push access

**Comment by Neubulae** [comment]
ramdisk is crobbed for burger's no-doing ohno
rip in peas

**Comment by shedaniel** [comment]
give me push access, i will commit bitcoin miner

**Comment by OroArmor** [comment]
No more shitposting please.

**Comment by hYdos** [comment]
yes
